/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import domain.PolicijskaUprava;
import javax.swing.JOptionPane;
import table_models.PUTableModel;
import controller.Controller;
import domain.Raskrsnica;
import java.util.ArrayList;
/**
 *
 * @author Stefan
 */
public class PretraziPUKritForm extends javax.swing.JDialog {

    /**
     * Creates new form PretraziPUKritForm
     */
    
    private void prepareGeneral() {
        this.remove(lblGrad);
        this.remove(comboGrad);
        this.remove(jScrollPane1);
        this.remove(lblRaskrsnica);
        this.remove(comboRaskrsnica);
        this.remove(jScrollPane2);
    }
    
    public PretraziPUKritForm(java.awt.Frame parent, boolean modal, String kriterijum) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretrazi Policijske Uprave");
        
        prepareGeneral();
        
        if(kriterijum.equals("Lokacija")) 
            prepareLokacija();
        else if(kriterijum.equals("Raskrsnica")) 
            prepareRaskrsnica();
    }
        
    private void prepareLokacija() {
        this.add(lblGrad);
        this.add(comboGrad);
        ucitajGradove();
        
        comboGrad.addActionListener( e -> {
            if(comboGrad.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Izaberite grad pu", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            this.add(jScrollPane1);
            try{
                tblUprave.setModel(new PUTableModel(new PolicijskaUprava((String)comboGrad.getSelectedItem(), 0)));
            }catch(Exception greska){
                JOptionPane.showMessageDialog(this, "Greska u prikazivanju policijske uprave","Greska",JOptionPane.ERROR_MESSAGE);
            }
        });
    }
    
    private void prepareRaskrsnica() {
        this.add(lblRaskrsnica);
        this.add(comboRaskrsnica);
        ucitajRaskrsnice();
        
        comboRaskrsnica.addActionListener( e -> {
            if(comboRaskrsnica.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Izaberite raskrsnicu", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            this.add(jScrollPane2);
            try{
                tblUprave1.setModel(new PUTableModel(new Raskrsnica((String) comboRaskrsnica.getSelectedItem(), "") ));
            }catch(Exception g){
                JOptionPane.showMessageDialog(this, "Greska u prikazivanju policijske uprave","Greska",JOptionPane.ERROR_MESSAGE);

            }
        });
    }
    
    
    private void ucitajRaskrsnice() {
        try{
        ArrayList<Raskrsnica> sveRas=Controller.getInstance().vratiListuSviRaskrsnica();
        ArrayList<String> raskrsnice = new ArrayList<>();
        for(Raskrsnica rr:sveRas){
            raskrsnice.add(rr.getNaziv());
        }
        
        for(String r : raskrsnice)
            comboRaskrsnica.addItem(r);
        comboRaskrsnica.setSelectedItem(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju raskrnica","Greska",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void ucitajGradove() {
        try{
            ArrayList<Raskrsnica> sveRask=Controller.getInstance().vratiListuSviRaskrsnica();
            ArrayList<String> gradovi = new ArrayList<>();
            for(Raskrsnica r:sveRask){
                if(!gradovi.contains(r.getGrad())){
                    gradovi.add(r.getGrad());
                }else{
                    continue;
                }
            }


            for(String grad : gradovi)
                comboGrad.addItem(grad);
            comboGrad.setSelectedItem(null);
        }catch(Exception gr){
            JOptionPane.showMessageDialog(this, "Greska pti ucitavanju gradova!","Greska",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public PretraziPUKritForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblGrad = new javax.swing.JLabel();
        comboGrad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUprave = new javax.swing.JTable();
        lblRaskrsnica = new javax.swing.JLabel();
        comboRaskrsnica = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUprave1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pretrazi Policijske Uprave");

        lblGrad.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblGrad.setText("Grad PU ");

        comboGrad.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        tblUprave.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUprave);

        lblRaskrsnica.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblRaskrsnica.setText("Raskrsnica");

        comboRaskrsnica.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        tblUprave1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblUprave1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGrad)
                        .addGap(47, 47, 47)
                        .addComponent(comboGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRaskrsnica)
                        .addGap(47, 47, 47)
                        .addComponent(comboRaskrsnica, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrad)
                            .addComponent(comboGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRaskrsnica)
                            .addComponent(comboRaskrsnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretraziPUKritForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretraziPUKritForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretraziPUKritForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretraziPUKritForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PretraziPUKritForm dialog = new PretraziPUKritForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboGrad;
    private javax.swing.JComboBox<String> comboRaskrsnica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGrad;
    private javax.swing.JLabel lblRaskrsnica;
    private javax.swing.JTable tblUprave;
    private javax.swing.JTable tblUprave1;
    // End of variables declaration//GEN-END:variables
}
