/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;
import domain.*;
import controller.Controller;
import javax.swing.JOptionPane;
/**
 *
 * @author Stefan
 */
public class PretraziPUForm extends javax.swing.JDialog {

    /**
     * Creates new form PretraziPUForm
     */
    public PretraziPUForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretrazi Policijsku Upravu");
        
        prepare();
        
        btnPretrazi.addActionListener( e -> {
            String naziv = txtNaziv.getText();
            
            if(naziv.equals("")) {
                JOptionPane.showMessageDialog(this, "Unesite naziv policijske uprave", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            PolicijskaUprava pu = Controller.getInstance().pretraziPolicijskaUprava(new PolicijskaUprava(naziv));
            
            if(pu == null) {
                txtID.setText("");
                txtGrad.setText("");
                txtOpstina.setText("");
                txtAdresa.setText("");
                JOptionPane.showMessageDialog(this, "Nema rezultata pretrage!", "Poruka", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            lblID.setVisible(true);
            txtID.setVisible(true);
            txtID.setText(pu.getId() + "");
            txtID.setEnabled(false);
            lblGrad.setVisible(true);
            txtGrad.setVisible(true);
            txtGrad.setText(pu.getGrad());
            txtGrad.setEnabled(false);
            lblOpstina.setVisible(true);
            txtOpstina.setVisible(true);
            txtOpstina.setText(pu.getOpstina());
            txtOpstina.setEnabled(false);
            lblAdresa.setVisible(true);
            txtAdresa.setVisible(true);
            txtAdresa.setText(pu.getAdresa());
            txtAdresa.setEnabled(false);
            
            
            
            
        });
        
    }
    
    private void prepare() {
        lblID.setVisible(false);
        txtID.setVisible(false);
        lblGrad.setVisible(false);
        txtGrad.setVisible(false);
        lblOpstina.setVisible(false);
        txtOpstina.setVisible(false);
        lblAdresa.setVisible(false);
        txtAdresa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        lblGrad = new javax.swing.JLabel();
        txtGrad = new javax.swing.JTextField();
        lblOpstina = new javax.swing.JLabel();
        txtOpstina = new javax.swing.JTextField();
        lblAdresa = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pretrazi Policijske Uprave");

        lblNaziv.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblNaziv.setText("Naziv PU");

        txtNaziv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblGrad.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblGrad.setText("Grad PU");

        txtGrad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblOpstina.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblOpstina.setText("Opstina PU");

        txtOpstina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblAdresa.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblAdresa.setText("Adresa PU");

        txtAdresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblID.setText("ID PU");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnPretrazi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnPretrazi.setText("Pretrazi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNaziv)
                            .addComponent(lblGrad)
                            .addComponent(lblOpstina)
                            .addComponent(lblAdresa)
                            .addComponent(lblID))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtNaziv)
                            .addComponent(txtGrad)
                            .addComponent(txtOpstina)
                            .addComponent(txtAdresa)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnPretrazi)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNaziv))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGrad)
                    .addComponent(txtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpstina)
                    .addComponent(txtOpstina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdresa)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnPretrazi)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretraziPUForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretraziPUForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretraziPUForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretraziPUForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PretraziPUForm dialog = new PretraziPUForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdresa;
    private javax.swing.JLabel lblGrad;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblOpstina;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtGrad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtOpstina;
    // End of variables declaration//GEN-END:variables
}
