/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;
import controller.Controller;
import domain.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Stefan
 */
public class PretraziVoziloForm extends javax.swing.JDialog {

    /**
     * Creates new form PretraziVoziloForm
     */
    public PretraziVoziloForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretraga vozila");
        prepare();
    }
    
    private void prepare() {
        lblId.setVisible(false);
        lblMarka.setVisible(false);
        lblModel.setVisible(false);
        txtID.setVisible(false);
        txtMarka.setVisible(false);
        txtModel.setVisible(false);
        
        btnPretraga.addActionListener(e -> {
            if(!check_reg()) {
                JOptionPane.showMessageDialog(this, "Neispravna registraciona oznaka!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Vozilo v = Controller.getInstance().pretraziVozilo(new Vozilo(txtRegistracija.getText()));
                
            if(v == null) {
                txtID.setText("");
                txtMarka.setText("");
                txtModel.setText("");
                JOptionPane.showMessageDialog(this, "Ne postoji rezultat pretrage!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }

            txtID.setVisible(true);
            txtID.setText(v.getId_vozilo()+"");
            txtID.setEnabled(false);
            lblId.setVisible(true);
            txtMarka.setVisible(true);
            txtMarka.setText(v.getMarka());
            txtMarka.setEnabled(false);
            lblMarka.setVisible(true);
            txtModel.setVisible(true);
            txtModel.setText(v.getModel());
            txtModel.setEnabled(false);
            lblModel.setVisible(true);
            
        });
    }
    
    private boolean check_reg() {
        String[] elems = txtRegistracija.getText().split("-");
        if(elems[0].length() != 2 || elems[2].length() != 2 || elems[1].length() < 3 || elems[1].length() > 5) 
            return false;

        char[] chars_1 = elems[0].toCharArray();
        for(char c : chars_1) {
            if(!Character.isLetter(c)) 
                return false;
        }

        char[] chars_2 = elems[1].toCharArray();
        for(char c : chars_2) {
            if(!Character.isDigit(c)) 
                return false;
        }
        
        char[] chars_3 = elems[2].toCharArray();
        for(char c : chars_3) {
            if(!Character.isLetter(c)) 
                return false;
        }
        
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRegistracija = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblMarka = new javax.swing.JLabel();
        txtMarka = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        btnPretraga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pretrazi Vozilo");

        jLabel2.setText("Registraciona Oznaka");

        lblId.setText("ID");

        lblMarka.setText("Marka");

        lblModel.setText("Model");

        btnPretraga.setText("Pretrazi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblId)
                    .addComponent(lblMarka)
                    .addComponent(lblModel))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(txtRegistracija)
                        .addComponent(txtID)
                        .addComponent(txtMarka)
                        .addComponent(txtModel, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                    .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarka)
                    .addComponent(txtMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnPretraga)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretraziVoziloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretraziVoziloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretraziVoziloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretraziVoziloForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PretraziVoziloForm dialog = new PretraziVoziloForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretraga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMarka;
    private javax.swing.JLabel lblModel;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMarka;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtRegistracija;
    // End of variables declaration//GEN-END:variables
}
