/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;
import javax.swing.JOptionPane;
import main.KategorijaKazna;
import controller.Controller;
import domain.*;

/**
 *
 * @author Stefan
 */
public class KreirajKaznaForm extends javax.swing.JDialog {

    /**
     * Creates new form KreirajKaznaForm
     */
    public KreirajKaznaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Kreiraj Kaznu");
        prepareForInsert();
        
        comboKategorija.addActionListener(e -> {
            if(KategorijaKazna.Kategorija_I.equals((KategorijaKazna)comboKategorija.getSelectedItem())) 
                txtIznos.setText("100000");
            else if (KategorijaKazna.Kategorija_II.equals((KategorijaKazna)comboKategorija.getSelectedItem()))
                txtIznos.setText("80000");
            else if(KategorijaKazna.Kategorija_III.equals((KategorijaKazna)comboKategorija.getSelectedItem()))
                txtIznos.setText("50000");
        });
    }
    
     public KreirajKaznaForm(java.awt.Frame parent, boolean modal, Kazna k) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Kreiraj Kaznu");
        prepareForUpdate(k);
        
        comboKategorija.addActionListener(e -> {
            if(KategorijaKazna.Kategorija_I.equals((KategorijaKazna)comboKategorija.getSelectedItem())) 
                txtIznos.setText("100000");
            else if (KategorijaKazna.Kategorija_II.equals((KategorijaKazna)comboKategorija.getSelectedItem()))
                txtIznos.setText("80000");
            else if(KategorijaKazna.Kategorija_III.equals((KategorijaKazna)comboKategorija.getSelectedItem()))
                txtIznos.setText("50000");
        });
        
        
        
    }
     
     private void prepareForUpdate(Kazna k) {
         lblTitle.setText("Promeni Kaznu");
         lblID.setVisible(true);
         txtID.setVisible(true);
         txtID.setText(k.getId_kazna()+"");
         txtID.setEnabled(false);
         
         txtNaziv.setText(k.getNaziv());
         ucitajKategorije();
         comboKategorija.setSelectedItem(k.getKategorija());
         txtIznos.setText(k.getIznos()+"");
         txtIznos.setEnabled(false);
         
         btnKreiraj.setVisible(false);
         btnPromeni.setVisible(true);
         
         btnPromeni.addActionListener(e -> {
            
            if(JOptionPane.showConfirmDialog(this, "Da li ste sigurni?", "Potvrda", JOptionPane.YES_NO_OPTION) != 0)
                return;

            if(Controller.getInstance().pretraziKazna(new Kazna(txtNaziv.getText())) != null) {
                JOptionPane.showMessageDialog(this, "Dati naziv kazne je zauzet!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if(comboKategorija.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Izaberite kategoriju kazne!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if(Controller.getInstance().promeniKazna(new Kazna(Long.parseLong(txtID.getText()) , txtNaziv.getText(), (KategorijaKazna)comboKategorija.getSelectedItem(), Double.parseDouble(txtIznos.getText())))) {
                JOptionPane.showMessageDialog(this, "Kazna je promenjena!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new PromeniKaznaForm(null, true).setVisible(true);
            }
            else 
                JOptionPane.showMessageDialog(this, "Greska pri promeni kazne!", "Greska", JOptionPane.ERROR_MESSAGE);
        });
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        lblKategorija = new javax.swing.JLabel();
        comboKategorija = new javax.swing.JComboBox<>();
        lblIznos = new javax.swing.JLabel();
        txtIznos = new javax.swing.JTextField();
        btnKreiraj = new javax.swing.JButton();
        btnPromeni = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblID.setText("ID");

        lblNaziv.setText("Naziv");

        lblKategorija.setText("Kategorija");

        lblIznos.setText("Iznos");

        btnKreiraj.setText("Kreiraj kaznu");

        btnPromeni.setText("Promeni kaznu");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("Kreiraj Kaznu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKreiraj)
                                .addGap(98, 98, 98)
                                .addComponent(btnPromeni))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblIznos)
                                    .addGap(33, 33, 33)
                                    .addComponent(txtIznos))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblKategorija)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboKategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblID)
                                        .addComponent(lblNaziv))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtID)
                                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKategorija)
                    .addComponent(comboKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIznos)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreiraj)
                    .addComponent(btnPromeni))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void prepareForInsert() {
        lblID.setVisible(false);
        txtID.setVisible(false);
        ucitajKategorije();
        txtIznos.setEnabled(false);
        btnPromeni.setVisible(false);
        
        btnKreiraj.addActionListener(e -> {
                      
            if(Controller.getInstance().pretraziKazna(new Kazna(txtNaziv.getText())) != null) {
                JOptionPane.showMessageDialog(this, "Naziv kazne je zauzet!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(comboKategorija.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Izaberite kategoriju kazne!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
           
            if(JOptionPane.showConfirmDialog(this, "Da li ste sigurni?", "Potvrda", JOptionPane.YES_NO_OPTION) != 0)
                return;
 
            if(Controller.getInstance().kreirajKazna(new Kazna(txtNaziv.getText(), (KategorijaKazna)comboKategorija.getSelectedItem(), Double.parseDouble(txtIznos.getText())))) 
                JOptionPane.showMessageDialog(this, "Kazna je kreirana!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            else {
                JOptionPane.showMessageDialog(this, "Greska pri kreiranju kazne!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(JOptionPane.showConfirmDialog(this, "Da li zelite uneti novu kaznu?", "Potvrda", JOptionPane.YES_NO_OPTION) != 0)
                this.setVisible(false);
            else
                prepareForNewInsert();
            
        });
    }
    
    private void prepareForNewInsert() {
        txtNaziv.setText("");
        comboKategorija.setSelectedItem(null);
        txtIznos.setText("");
    }
    
    private boolean check_naziv() {
        String naziv = txtNaziv.getText();
            
        if(naziv.equals(""))
            return false;
        
        char[] chars = naziv.toCharArray();
        for(char c : chars) {
            if(!Character.isLetter(c))
                return false;
        }
        
        return true;
    }
    
    private void ucitajKategorije() {
        for (KategorijaKazna k : KategorijaKazna.values()) 
            comboKategorija.addItem(k); 
        comboKategorija.setSelectedItem(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KreirajKaznaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KreirajKaznaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KreirajKaznaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KreirajKaznaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KreirajKaznaForm dialog = new KreirajKaznaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JComboBox<KategorijaKazna> comboKategorija;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIznos;
    private javax.swing.JLabel lblKategorija;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
}
