/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;
import javax.swing.JOptionPane;
import domain.*;
import controller.Controller;
import java.util.ArrayList;
import table_models.RaskrsnicaTableModel;

/**
 *
 * @author Stefan
 */
public class PretraziRaskrsnicaForm extends javax.swing.JDialog {

    /**
     * Creates new form PretraziRaskrsnicaForm
     */
    
    private void prepareGeneral() {
        this.remove(lblNaziv);
        this.remove(txtNaziv);
        this.remove(lblGrad);
        this.remove(comboGradovi);
        this.remove(btnPretrazi);
        this.remove(lblGrad1);
        this.remove(comboGradovi1);
        this.remove(jScrollPane1);
    }
    
    private void prepareLokacija() {
        this.add(lblGrad1);
        this.add(comboGradovi1);
        ucitajGradove("Lokacija");
        
        comboGradovi1.addActionListener( e -> {
            if(comboGradovi1.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Izaberite grad!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            this.add(jScrollPane1);
            tblRaskrsnice.setModel(new RaskrsnicaTableModel(new Raskrsnica((String)comboGradovi1.getSelectedItem())));
        });
    }
    
    private void prepareNaziv() {
        this.add(lblNaziv);
        this.add(txtNaziv);
        this.add(lblGrad);
        this.add(comboGradovi);
        ucitajGradove("Naziv");
        comboGradovi.setEnabled(false);
        this.add(btnPretrazi);
        
         btnPretrazi.addActionListener( e -> {
            if(txtNaziv.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Unesite naziv", "Greska", JOptionPane.ERROR_MESSAGE);
                comboGradovi.setSelectedItem(null);
                return;
            }
            
            Raskrsnica r = Controller.getInstance().pretraziRaskrsnica(new Raskrsnica(txtNaziv.getText(), ""));
            if(r == null) {
                JOptionPane.showMessageDialog(this, "Nema rezultata pretrage", "Poruka", JOptionPane.INFORMATION_MESSAGE);
                comboGradovi.setSelectedItem(null);
                return;
            } 
            comboGradovi.setSelectedItem(r.getGrad());
        });
        
    }
    
    public PretraziRaskrsnicaForm(java.awt.Frame parent, boolean modal, String kriterijum) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretrazi Raskrsnicu");
        
        prepareGeneral();
        
        switch(kriterijum) {
            case "Naziv":
                prepareNaziv();
            break;
            
            case "Lokacija":
                prepareLokacija();
            break;
        }
    }
    
    
    public PretraziRaskrsnicaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
      
    }
   
    
    private void ucitajGradove(String s) {
        ArrayList<String> gradovi = Controller.getInstance().ucitajGradove();
        
        if(s.equals("Naziv")) {
            for(String grad : gradovi)
                comboGradovi.addItem(grad);
            comboGradovi.setSelectedItem(null);
        } else {
            for(String grad : gradovi)
                comboGradovi1.addItem(grad);
            comboGradovi1.setSelectedItem(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        lblGrad = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        txtNaziv = new javax.swing.JTextField();
        comboGradovi = new javax.swing.JComboBox<>();
        lblGrad1 = new javax.swing.JLabel();
        comboGradovi1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRaskrsnice = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pretrazi Raskrsnicu");

        lblNaziv.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblNaziv.setText("Naziv Raskrsnice");

        lblGrad.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblGrad.setText("Grad");

        btnPretrazi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnPretrazi.setText("Pretrazi");

        txtNaziv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        comboGradovi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblGrad1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblGrad1.setText("Grad");

        comboGradovi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblRaskrsnice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblRaskrsnice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRaskrsnice);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNaziv)
                            .addComponent(lblGrad))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNaziv)
                            .addComponent(comboGradovi, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnPretrazi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGrad1)
                        .addGap(31, 31, 31)
                        .addComponent(comboGradovi1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNaziv)
                    .addComponent(lblGrad1)
                    .addComponent(comboGradovi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrad)
                            .addComponent(comboGradovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115)
                        .addComponent(btnPretrazi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretraziRaskrsnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretraziRaskrsnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretraziRaskrsnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretraziRaskrsnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PretraziRaskrsnicaForm dialog = new PretraziRaskrsnicaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JComboBox<String> comboGradovi;
    private javax.swing.JComboBox<String> comboGradovi1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrad;
    private javax.swing.JLabel lblGrad1;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JTable tblRaskrsnice;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
}
