/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import javax.swing.JOptionPane;
import table_models.VoziloTableModel;
import domain.*;
import java.util.ArrayList;

/**
 *
 * @author Stefan
 */
public class PretraziVoziloKritForm extends javax.swing.JDialog {

    /**
     * Creates new form PretraziVoziloKritForm
     */
    private void prepareGeneral() {
        this.remove(lblGrad);
        this.remove(lblMarka);
        this.remove(comboGrad);
        this.remove(comboMarka);
        this.remove(jScrollPane1);
        this.remove(jScrollPane2);
    }
    
    public PretraziVoziloKritForm(java.awt.Frame parent, boolean modal, String kriterijum) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretrazi Vozila");
        
        prepareGeneral();
        
        if(kriterijum.equals("Vlasnik"))
            prepareVlasnik();
        else if(kriterijum.equals("Marka")) 
            prepareMarka();
    }
    
    private void prepareVlasnik() {
        this.add(lblGrad);
        this.add(comboGrad);
        
        ucitajGradove();
        comboGrad.addActionListener( e -> {
            if(comboGrad.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Izaberite grad/prebivaliste", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            this.add(jScrollPane1);
            tblVozila1.setModel(new VoziloTableModel(new Vlasnik((String)comboGrad.getSelectedItem(), 0)));
        });
    }
    
    private void prepareMarka() {
        this.add(lblMarka);
        this.add(comboMarka);
        
        ucitajMarke();
        comboMarka.addActionListener( e -> {
            if(comboMarka.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Izaberite marku vozila!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            this.add(jScrollPane2);
            tblVozila2.setModel(new VoziloTableModel(new Vozilo((String) comboMarka.getSelectedItem(), 0)));
        });
    }
    
    private void ucitajGradove() {
        ArrayList<String> gradovi = Controller.getInstance().ucitajGradove();
        
        for(String grad : gradovi)
            comboGrad.addItem(grad);
        comboGrad.setSelectedItem(null);
    }
    
    private void ucitajMarke() {
         ArrayList<String> marke = Controller.getInstance().ucitajMarke();
        
        for(String marka : marke)
            comboMarka.addItem(marka);
        comboMarka.setSelectedItem(null);
    }
    
    public PretraziVoziloKritForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblGrad = new javax.swing.JLabel();
        comboGrad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVozila1 = new javax.swing.JTable();
        lblMarka = new javax.swing.JLabel();
        comboMarka = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVozila2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pretrazi Vozila");

        lblGrad.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblGrad.setText("Grad / Prebivaliste Vlasnika:");

        comboGrad.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        tblVozila1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVozila1);

        lblMarka.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblMarka.setText("Marka Vozila:");

        comboMarka.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        tblVozila2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblVozila2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(lblGrad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMarka)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(comboGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboMarka, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(385, 385, 385))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrad)
                    .addComponent(lblMarka))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretraziVoziloKritForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretraziVoziloKritForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretraziVoziloKritForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretraziVoziloKritForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PretraziVoziloKritForm dialog = new PretraziVoziloKritForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboGrad;
    private javax.swing.JComboBox<String> comboMarka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGrad;
    private javax.swing.JLabel lblMarka;
    private javax.swing.JTable tblVozila1;
    private javax.swing.JTable tblVozila2;
    // End of variables declaration//GEN-END:variables
}
