/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import domain.Kazna;
import javax.swing.JOptionPane;
import main.KategorijaKazna;
import controller.Controller;
import java.util.ArrayList;
import table_models.KaznaTableModel;

/**
 *
 * @author Stefan
 */
public class PretraziKaznaForm extends javax.swing.JDialog {

    private void prepareGeneral() {
        this.remove(lblKategorija);
        this.remove(lblNaziv);
        this.remove(lblIznos);
        this.remove(comboKategorija);
        this.remove(txtNazivKazna);
        this.remove(txtIznos);
        this.remove(btnPretragaKazna);
        this.remove(lblKategorija1);
        this.remove(comboKategorija1);
        this.remove(jScrollPane1);
    }
    /**
     * Creates new form PretraziKaznaForm
     */
    public PretraziKaznaForm(java.awt.Frame parent, boolean modal, String kriterijum) { 
        super(parent, modal); 
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretrazi kaznu");
        prepareGeneral();
        
        switch(kriterijum) {
            case "Naziv":
                prepareNaziv();
            break;
            
            case "Kategorija":
                prepareKategorija();
            break;
        }
    }
    
    private void prepareKategorija() {
        this.add(lblKategorija1);
        this.add(comboKategorija1);
        ucitajKategorije("Kategorija");
        
        comboKategorija1.addActionListener( e -> {
            if(comboKategorija1.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Izaberite kategoriju kazne!", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            this.add(jScrollPane1);
            tblKazne.setModel(new KaznaTableModel(new Kazna((KategorijaKazna)comboKategorija1.getSelectedItem())));
            
        });
        
    }
    
    private void prepareNaziv() {
        this.add(lblNaziv);
        this.add(txtNazivKazna);
        this.add(btnPretragaKazna);
        this.add(lblKategorija);
        this.add(comboKategorija);
        comboKategorija.setEnabled(false);
        this.add(lblIznos);
        this.add(txtIznos);
        txtIznos.setEnabled(false);
        
        
        btnPretragaKazna.addActionListener( e -> {
            if(!check_naziv()) {
                JOptionPane.showMessageDialog(this, "Neispravan unos naziva kazne", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Kazna k = Controller.getInstance().pretraziKazna(new Kazna(txtNazivKazna.getText()));
            if(k != null) {
                ucitajKategorije("Naziv");
                comboKategorija.setSelectedItem(k.getKategorija());
                comboKategorija.setEnabled(false);
                txtIznos.setText(k.getIznos()+"");
                txtIznos.setEnabled(false);
            } else {
                comboKategorija.setSelectedItem(null);
                txtIznos.setText("");
                JOptionPane.showMessageDialog(this, "Nema rezultata pretrage!", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            }
        });
    }
    
    public PretraziKaznaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    
    
    private void ucitajKategorije(String s) {
        switch(s) {
            case "Naziv":
                for(KategorijaKazna elem : KategorijaKazna.values())
                comboKategorija.addItem(elem);
                comboKategorija.setSelectedItem(null);
            break;

            case "Kategorija":
            for(KategorijaKazna elem : KategorijaKazna.values())
                comboKategorija1.addItem(elem);

            comboKategorija1.setSelectedItem(null);
            break;
        }
        
    }
    
    private boolean check_naziv() {
        String naziv_kazne = txtNazivKazna.getText();
        if(naziv_kazne.equals(""))
            return false;
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPretragaKazna = new javax.swing.JButton();
        lblNaziv = new javax.swing.JLabel();
        txtNazivKazna = new javax.swing.JTextField();
        lblKategorija = new javax.swing.JLabel();
        lblIznos = new javax.swing.JLabel();
        comboKategorija = new javax.swing.JComboBox<>();
        txtIznos = new javax.swing.JTextField();
        lblKategorija1 = new javax.swing.JLabel();
        comboKategorija1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKazne = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Pretrazi Kazne");

        btnPretragaKazna.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPretragaKazna.setText("Pretrazi");

        lblNaziv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNaziv.setText("Naziv Kazne");

        txtNazivKazna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblKategorija.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKategorija.setText("Kategorija Kazne");

        lblIznos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIznos.setText("Iznos Kazne");

        comboKategorija.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtIznos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblKategorija1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKategorija1.setText("Kategorija Kazne");

        comboKategorija1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblKazne.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKazne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKazne);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKategorija)
                        .addGap(18, 18, 18)
                        .addComponent(comboKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNaziv)
                                .addGap(46, 46, 46)
                                .addComponent(txtNazivKazna, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIznos)
                                .addGap(48, 48, 48)
                                .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPretragaKazna))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKategorija1)
                                .addGap(18, 18, 18)
                                .addComponent(comboKategorija1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivKazna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNaziv)
                    .addComponent(lblKategorija1)
                    .addComponent(comboKategorija1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKategorija)
                            .addComponent(comboKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIznos)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnPretragaKazna)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretraziKaznaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretraziKaznaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretraziKaznaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretraziKaznaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PretraziKaznaForm dialog = new PretraziKaznaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretragaKazna;
    private javax.swing.JComboBox<KategorijaKazna> comboKategorija;
    private javax.swing.JComboBox<KategorijaKazna> comboKategorija1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIznos;
    private javax.swing.JLabel lblKategorija;
    private javax.swing.JLabel lblKategorija1;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JTable tblKazne;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextField txtNazivKazna;
    // End of variables declaration//GEN-END:variables
}
