/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;
import controller.Controller;
import javax.swing.JOptionPane;
import domain.*;
import java.util.ArrayList;

/**
 *
 * @author Stefan
 */
public class UbaciRaskrsnicaForm extends javax.swing.JDialog {

    /**
     * Creates new form UbaciRaskrsnicaForm
     */
    
    private void prepareForInsert() {
        setTitle("Ubaci Raskrsnicu");
        lblTitle.setText("Kreiraj Raskrsnicu");
        lblID.setVisible(false);
        txtID.setVisible(false);
        ucitajGradove();
        btnPromeni.setVisible(false);
    }
    
    private void ucitajGradove() {
        ArrayList<String> gradovi = Controller.getInstance().ucitajGradove();
        
        for(String grad : gradovi)
            comboGradovi.addItem(grad);
        
        comboGradovi.setSelectedItem(null);
    }
    
    public UbaciRaskrsnicaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        prepareForInsert();
        
        btnKreiraj.addActionListener( e-> {
            String naziv = txtNazivRaskrsnice.getText();
            String grad = (String)comboGradovi.getSelectedItem();
        
            if(checkFields(naziv, grad)) {
                if(JOptionPane.showConfirmDialog(this, "Da li ste sigurni?", "Potvrda", JOptionPane.YES_NO_OPTION) == 0) {
                    if(!Controller.getInstance().daLiPostojiRaskrsnica(naziv, grad)) {
                        if(Controller.getInstance().ubaciRaskrsnica(new Raskrsnica(naziv, grad))) {
                            JOptionPane.showMessageDialog(this, "Raskrsnica sacuvana!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);

                            if(JOptionPane.showConfirmDialog(this, "Novi unos?", "Potvrda", JOptionPane.YES_NO_OPTION) == 0) {
                                txtNazivRaskrsnice.setText("");
                                comboGradovi.setSelectedItem(null);
                            } else 
                                this.setVisible(false);
                        } else 
                            JOptionPane.showMessageDialog(this, "Raskrsnica nije sacuvana!", "Greska", JOptionPane.ERROR_MESSAGE);
                    } else 
                        JOptionPane.showMessageDialog(this, "Raskrsnica sa unetim nazivom vec postoji", "Greska", JOptionPane.ERROR_MESSAGE);
                }
            } else
                JOptionPane.showMessageDialog(this, "Neispravni podaci!", "Greska", JOptionPane.ERROR_MESSAGE);
            
        });
        
    }
    
    public UbaciRaskrsnicaForm(java.awt.Frame parent, boolean modal, Raskrsnica r) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        prepareForUpdate(r);
        
        btnPromeni.addActionListener( e -> {
            String naziv = txtNazivRaskrsnice.getText();
            String grad = (String)comboGradovi.getSelectedItem();
            if(JOptionPane.showConfirmDialog(this, "Da li ste sigurni?", "Potvrda", JOptionPane.YES_NO_OPTION) != 0)
                return;
            if(Controller.getInstance().promeniRaskrsnica(new Raskrsnica(Long.parseLong(txtID.getText()), naziv, grad))) {
                JOptionPane.showMessageDialog(this, "Raskrsnica promenjena.", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                new PromeniRaskrsnicaForm(null, true).setVisible(true);
            } else 
                JOptionPane.showMessageDialog(this, "Greska pri promeni raskrsnice", "Greska", JOptionPane.ERROR_MESSAGE);
        });
                
    }
    
    private void prepareForUpdate(Raskrsnica r) {
        setTitle("Promeni raskrsnicu");
        lblTitle.setText("Promeni Raskrsnicu");
        lblID.setVisible(true);
        txtID.setVisible(true);
        txtID.setText(r.getId_raskrsnica()+"");
        txtID.setEnabled(false);
        txtNazivRaskrsnice.setText(r.getNaziv());
        ucitajGradove() ;
        comboGradovi.setSelectedItem(r.getGrad());
        btnKreiraj.setVisible(false);
    }

    private boolean checkFields(String naziv, String grad) {
        
        if(naziv.equals("") || grad == null)
            return false;
        
        if(naziv.length() < 3)
            return false;
        
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNazivRaskrsnice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnKreiraj = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnPromeni = new javax.swing.JButton();
        comboGradovi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("Kreiraj Raskrsnicu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Naziv Raskrsnice");

        txtNazivRaskrsnice.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Grad Raskrsnice");

        btnKreiraj.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnKreiraj.setText("Kreiraj");

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblID.setText("ID Raskrsnice");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        btnPromeni.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnPromeni.setText("Promeni");

        comboGradovi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNazivRaskrsnice)
                                    .addComponent(comboGradovi, 0, 334, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addGap(47, 47, 47)
                                .addComponent(txtID))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnKreiraj)
                        .addGap(120, 120, 120)
                        .addComponent(btnPromeni)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivRaskrsnice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboGradovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKreiraj)
                    .addComponent(btnPromeni))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UbaciRaskrsnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UbaciRaskrsnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UbaciRaskrsnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UbaciRaskrsnicaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UbaciRaskrsnicaForm dialog = new UbaciRaskrsnicaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JComboBox<String> comboGradovi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNazivRaskrsnice;
    // End of variables declaration//GEN-END:variables
}
